name: cascade_widget
description: "A versatile Flutter cascade selection widget, offering multi-level cascading dropdowns with single and multiple selection options. Ideal for web and desktop applications."
version: 3.0.1
homepage: https://github.com/superSong-hello/cascade_widget
repository: https://github.com/superSong-hello/cascade_widget

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - cascade
  - dropdown
  - multiselect
  - form
  - select

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
#  plugin:
#    platforms:
#      default_package: lib
